### PR TITLE
Added Server Manager class & Format mazes (adding proper boundaries/exits) in Middleware

### PR DESCRIPTION
**Pull request by aarya-bhatia**
- Added a server manager class to handle all MG operations and simplify the code in app.py
- Using connection class to maintain DB connection
- Added my maze generators to the project and set them up with middleware
- minor refactor and changes
- removes faulty servers from database on error
- maze, MG class to simplify creation of new MGs

### CODE REVIEW

**Comment by PeterYR** [comment]
I like the encapsulating of Mongo logic. A shorter `app.py` is always nice lol.

Though I'm not sure the modules in your `maze` folder would be very useful for the front-end. To me it seems like they're more for the back-end MGs. Something similar but smaller might be useful for validating incoming maze data though (making sure walls exist, making sure exits are where they should be...).

Also, the current main branch has a `maze_generators` folder where I put one of my MGs for testing. Perhaps rename your `Maze-Generators` folder to that, and merge them?

**Comment by aarya-bhatia** [comment]
@PeterYR Okay, I will put my MG's in a maze_generators folder. I am using my maze class only in the MGs right now, but I think it can be extended for the middleware to validate the incoming mazes and also quickly add/remove walls. I have the add_boundary function in the maze class which automatically sets walls on the boundary and creates exits in the center of every 7x7 unit. (I will make some small adjustments before it's ready to use)

**Comment by pcrain** [comment]
@aarya-bhatia Your changes look good so far! :smile: Can you ping me once you've finished so I can give them a look over before merging? Thanks!

**Comment by aarya-bhatia** [comment]
@pcrain Hi, I just fixed all the merge conflicts, and ran the code without errors! I think my feature is complete now.

**Comment by pcrain** [comment]
@aarya-bhatia The code you pulled and merged doesn't seem to include the new MongoDB storage of the maze generators, and I'm not sure why :open_mouth: I am trying to resolve this myself, but might end up having to merge your commits manually.

**Comment by aarya-bhatia** [comment]
Hi @pcrain, the maze generators are stored in the servers module. Is there something else I missed?

**Comment by pcrain** [comment]
Yeah, it took me far longer than I'd like to admit to realize that. :sweat_smile: Your code did remove logic for using the cached maze segments somewhere along the line, but I think I fixed that by just adding back in a few removed lines of code. Thanks! 😃

**Comment by aarya-bhatia** [comment]
Thank you @pcrain! Maybe I should write some documentation to make things easier to understand 😄

**Pull request merged**
